### ISSUE TITLE
Limit exposure time

### ISSUE THREAD

**Issue by iftahnaf** [Ar-Ray-code/picamera_ros2#6]
Hi,

Thanks for this repository @Ar-Ray-code, you did an awesome work here.

Is there a way to set the minimum and maximum exposure time?
I'm using the ov9281 sensor, Bookworm OS. My image is saturated, so I though to limit the maximum exposure time and reduce the minimum exposure time.

I tried to set:
```cpp
this->camera_->options->setExposureMode(Exposure_Modes::EXPOSURE_SHORT);
```

but its not enough for me.

didn't manage to work with the `capturePhoto` function.

Thanks in advance.

**Comment by Ar-Ray-code** [comment]
Hello.

Thank you for your report. The current version of libcamera may be different from when this repository was created, so we will start working on it as soon as the current project is finished. (but that will likely be after April :disappointed: ) 


There is probably a C++ wrapper for the RaspberryPi [here (raspberrypi/rpicam-apps)](https://github.com/raspberrypi/rpicam-apps), so you can try that first.

Any additional hardware requirements or benchmarking methods would help me get started on the fix sooner, and any PR would be greatly appreciated.

Thanks.

**Comment by iftahnaf** [comment]
Thanks for the quick answer.

I did manage to use the `shutter` option to limit the exposure time and the image is not longer saturated.
I'll add this as a new parameter in a new PR.

Thanks again.
